name: Deploy MultiCloud App to AWS EC2

on:
  push:
    branches:
      - main  # Se activa solo cuando subes cambios a la rama principal

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout del código
      uses: actions/checkout@v3

    - name: Configurar llave SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.AWS_SSH_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H ${{ secrets.AWS_EC2_IP }} >> ~/.ssh/known_hosts

    - name: Desplegar archivos por SCP a la EC2
      run: |
        # Copia tus archivos de código directo al directorio de tu servidor en AWS
        scp -r ./index.html ./login.html ./server.js ./styles.css ${{ secrets.AWS_USER }}@${{ secrets.AWS_EC2_IP }}:~/app-inacap/

    - name: Reiniciar la aplicación en el servidor remoto
      run: |
        ssh ${{ secrets.AWS_USER }}@${{ secrets.AWS_EC2_IP }} "
          cd ~/app-inacap
          npm install --production
          pm2 restart server || npx pm2 start server.js --name 'app-inacap'
        "